import type { V2_MetaFunction } from '@remix-run/node'
import type { ReactElement } from 'react'

import { Page } from '~/components/page'

export const meta: V2_MetaFunction = () => {
  return [
    {
      title: 'About — Steam Revenue Calculator'
    },
    {
      property: 'og:title',
      content: 'About — Steam Revenue Calculator'
    },
    {
      name: 'description',
      content: 'Learn about Steam Revenue Calculator — the tool for estimating game revenue on Steam. Built for game developers, marketers, and gaming enthusiasts.'
    },
    {
      property: 'og:description',
      content: 'Learn about Steam Revenue Calculator — the tool for estimating game revenue on Steam. Built for game developers, marketers, and gaming enthusiasts.'
    },
    {
      name: 'og:url',
      content: 'https://steam-revenue-calculator.com/about'
    },
    {
      tagName: 'link',
      rel: 'canonical',
      href: 'https://steam-revenue-calculator.com/about'
    }
  ]
}

export default function AboutRoute(): ReactElement {
  return (
    <Page>
      <div className="space-y-8 max-w-2xl leading-loose">
        <h1 className="text-3xl md:text-4xl font-poppins font-bold">About</h1>
        <div>
          Welcome to Steam Revenue Calculator, your go-to tool for estimating
          the revenue generated by any game on Steam. Whether you're a game
          developer looking to gauge the financial success of your latest
          release, a marketer analyzing market trends, or a gaming enthusiast
          curious about the financial aspects of your favorite games, our
          calculator provides the insights you need.
        </div>
        <div>
          For any inquiries or feedback, feel free to reach out to us at
          contact@steam-revenue-calculator.com. We are always here to assist
          you!
        </div>
        <div className="font-medium">Steam Revenue Calculator Team</div>
      </div>
    </Page>
  )
}
